// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: server/pb/server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalServerClient is the client API for InternalServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServerClient interface {
	Query(ctx context.Context, in *InternalRequest, opts ...grpc.CallOption) (*InternalResponse, error)
}

type internalServerClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServerClient(cc grpc.ClientConnInterface) InternalServerClient {
	return &internalServerClient{cc}
}

func (c *internalServerClient) Query(ctx context.Context, in *InternalRequest, opts ...grpc.CallOption) (*InternalResponse, error) {
	out := new(InternalResponse)
	err := c.cc.Invoke(ctx, "/server.InternalServer/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServerServer is the server API for InternalServer service.
// All implementations must embed UnimplementedInternalServerServer
// for forward compatibility
type InternalServerServer interface {
	Query(context.Context, *InternalRequest) (*InternalResponse, error)
	mustEmbedUnimplementedInternalServerServer()
}

// UnimplementedInternalServerServer must be embedded to have forward compatible implementations.
type UnimplementedInternalServerServer struct {
}

func (UnimplementedInternalServerServer) Query(context.Context, *InternalRequest) (*InternalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedInternalServerServer) mustEmbedUnimplementedInternalServerServer() {}

// UnsafeInternalServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServerServer will
// result in compilation errors.
type UnsafeInternalServerServer interface {
	mustEmbedUnimplementedInternalServerServer()
}

func RegisterInternalServerServer(s grpc.ServiceRegistrar, srv InternalServerServer) {
	s.RegisterService(&InternalServer_ServiceDesc, srv)
}

func _InternalServer_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServerServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.InternalServer/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServerServer).Query(ctx, req.(*InternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalServer_ServiceDesc is the grpc.ServiceDesc for InternalServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.InternalServer",
	HandlerType: (*InternalServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _InternalServer_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/pb/server.proto",
}
